[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2022"
default_run = "advent_of_code"
publish = "false"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
